import { addSyncIssue, patchExternalSourceRecord, readExternalSourceRecords } from './store';
import { clearExternalSourceCache } from './cache';
export type BackgroundSyncJob={id:string;kind:'drive-changes'|'source-refresh';sourceKey?:string;state:'pending'|'running'|'completed'|'failed';createdAt:number;attempts:number;error?:string};
const KEY='local-notion:external-background-sync-v1'; let running=false;
function read():BackgroundSyncJob[]{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function write(v:BackgroundSyncJob[]){localStorage.setItem(KEY,JSON.stringify(v.slice(-200)))}
export const readBackgroundSyncJobs=()=>read().sort((a,b)=>b.createdAt-a.createdAt);
export function enqueueBackgroundSync(kind:BackgroundSyncJob['kind'],sourceKey?:string){const jobs=read();const duplicate=jobs.some(x=>x.kind===kind&&x.sourceKey===sourceKey&&(x.state==='pending'||x.state==='running'));if(!duplicate)write([...jobs,{id:`sync-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,kind,sourceKey,state:'pending',createdAt:Date.now(),attempts:0}]);void processBackgroundSyncQueue();}
export async function processBackgroundSyncQueue():Promise<void>{if(running)return;running=true;try{let jobs=read();for(const job of jobs.filter(x=>x.state==='pending').slice(0,10)){jobs=read().map(x=>x.id===job.id?{...x,state:'running',attempts:x.attempts+1}:x);write(jobs);try{if(job.kind==='drive-changes'){const result=await window.localNotion.googleWorkspace.syncDriveChanges();const records=readExternalSourceRecords();for(const change of result.changes){const key=`drive:${change.fileId}`;const record=records.find(x=>x.key===key);if(!record)continue;if(change.removed){patchExternalSourceRecord(key,{syncState:'removed',lastSyncedAt:result.syncedAt});addSyncIssue({sourceKey:key,providerId:'drive',kind:'removed',message:`${record.title} はGoogle Drive側で削除されました。`});}else if(change.file){const changed=record.current.timestamp!==Date.parse(change.file.modifiedTime||'');patchExternalSourceRecord(key,{syncState:changed?'conflict':'synced',lastSyncedAt:result.syncedAt});if(changed)addSyncIssue({sourceKey:key,providerId:'drive',kind:'conflict',message:`${record.title} に更新があります。差分を確認してください。`});}clearExternalSourceCache('search:drive:');}}else if(job.sourceKey){patchExternalSourceRecord(job.sourceKey,{syncState:'synced',lastSyncedAt:Date.now(),lastError:undefined});}jobs=read().map(x=>x.id===job.id?{...x,state:'completed',error:undefined}:x);write(jobs);}catch(error){const message=error instanceof Error?error.message:String(error);jobs=read().map(x=>x.id===job.id?{...x,state:'failed',error:message}:x);write(jobs);if(job.sourceKey)patchExternalSourceRecord(job.sourceKey,{syncState:'failed',lastError:message});addSyncIssue({sourceKey:job.sourceKey,providerId:'drive',kind:message.includes('401')?'auth':message.includes('403')?'permission':'fetch',message});}}}finally{running=false;}}
export function retryBackgroundSyncJob(id:string){write(read().map(x=>x.id===id?{...x,state:'pending',error:undefined}:x));void processBackgroundSyncQueue();}
