import React,{useEffect,useMemo,useRef,useState}from"react";
import type{PageBundle,PageWithLock,WorkspaceDatabase}from"../../../../shared/types";
import{auditWebProject,designSuggestions,qualityScore}from"../../webBuilder/audit";
import{WEB_COMPONENTS}from"../../webBuilder/components";
import{compileWebProject,escapeHtml,htmlToText}from"../../webBuilder/compiler";
import{applyDesignerPrompt}from"../../webBuilder/designer";
import{exportProjectZip,exportSingleHtml}from"../../webBuilder/exporter";
import{DEFAULT_THEME,normalizeWebProject,switchWebPage,syncActivePage}from"../../webBuilder/model";
import{addLocalSource,localSourceBindingKeys,localSourceTag,readLocalWebFile}from"../../webBuilder/localFiles";
import{buildDeployGuide,compareVersions,makeBinding,makeSharedComponent,optimizeLayout}from"../../webBuilder/platform";
import{applyUserTemplate,autoLayoutCss,BUILTIN_PLUGINS,createUserTemplate,motionCss}from"../../webBuilder/ux";
import{createWebProject,deleteWebProject,queueWebProjectForWhiteboard,readActiveWebProjectId,readWebProjects,saveWebProject,setActiveWebProjectId}from"../../webBuilder/store";
import{WEB_TEMPLATES}from"../../webBuilder/templates";
import type{WebAuditIssue,WebBuilderPanel,WebCodeTab,WebConsoleEntry,WebPage,WebPreviewDevice,WebProject,WebProjectLink}from"../../webBuilder/types";
const DEVICE_WIDTH:Record<WebPreviewDevice,number|undefined>={desktop:undefined,tablet:768,mobile:390,iphone:430,ipad:820,macbook:1280,wide:1600};
const PANEL_LABEL:Record<WebBuilderPanel,string>={components:"部品",navigator:"構造",properties:"プロパティ",theme:"テーマ",assets:"素材",pages:"ページ",data:"データ",responsive:"レスポンシブ",quality:"品質",history:"履歴",templates:"型",plugins:"拡張",ai:"AI",publish:"公開"};
const codeLabel:Record<WebCodeTab,string>={html:"HTML",css:"CSS",javascript:"JavaScript"};
const sourceMarker=(link:Pick<WebProjectLink,"kind"|"id">)=>`${link.kind}:${encodeURIComponent(link.id)}`;const escapeRegExp=(v:string)=>v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const wrapLinkedSnapshot=(link:Pick<WebProjectLink,"kind"|"id"|"snapshot">)=>`<!-- LN-SOURCE:${sourceMarker(link)}:START -->\n${link.snapshot}\n<!-- LN-SOURCE:${sourceMarker(link)}:END -->`;
const linkedSnapshotPattern=(link:Pick<WebProjectLink,"kind"|"id">)=>new RegExp(`\\s*<!-- LN-SOURCE:${escapeRegExp(sourceMarker(link))}:START -->[\\s\\S]*?<!-- LN-SOURCE:${escapeRegExp(sourceMarker(link))}:END -->\\s*`,"g");
function removeLinkedSnapshot(html:string,link:WebProjectLink){const marked=html.replace(linkedSnapshotPattern(link),"\n");if(marked!==html)return marked.replace(/\n{3,}/g,"\n\n").trim();if(html.includes(link.snapshot))return html.replace(link.snapshot,"").trim();return html.replace(new RegExp(`<section[^>]*data-source-id=["']${escapeRegExp(link.id)}["'][\\s\\S]*?<\\/section>`,"g"),"").trim()}
function replaceLinkedSnapshot(html:string,previous:WebProjectLink,next:WebProjectLink){const pattern=linkedSnapshotPattern(previous);return pattern.test(html)?html.replace(pattern,`\n\n${wrapLinkedSnapshot(next)}\n\n`):html.includes(previous.snapshot)?html.replace(previous.snapshot,wrapLinkedSnapshot(next)):`${html.trim()}\n\n${wrapLinkedSnapshot(next)}`.trim()}
function databaseSnapshot(database:WorkspaceDatabase){const props=database.properties.slice(0,6);return `<section class="linked-database" data-source-id="${escapeHtml(database.id)}"><h2>${escapeHtml(database.title)}</h2><table><thead><tr>${props.map(p=>`<th>${escapeHtml(p.name)}</th>`).join("")}</tr></thead><tbody>${database.rows.slice(0,30).map(r=>`<tr>${props.map(p=>`<td>${escapeHtml(String(r.cells?.[p.id]??""))}</td>`).join("")}</tr>`).join("")}</tbody></table></section>`}
function parseNavigator(html:string){return[...html.matchAll(/<(section|header|main|footer|article|nav|h1|h2|h3)(?:\s+[^>]*)?>([\s\S]*?)<\/\1>/gi)].slice(0,100).map((m,i)=>({id:`node:${i}`,tag:m[1].toLowerCase(),title:htmlToText(m[2]).slice(0,48)||m[1],index:m.index??0}))}
function selectorForTag(tag:string){return tag==="body"?"body":tag.startsWith(".")?tag:`${tag}`}
async function copyText(value:string){const clipboard=globalThis.navigator?.clipboard;if(clipboard){await clipboard.writeText(value);return}const textarea=document.createElement("textarea");textarea.value=value;textarea.style.position="fixed";textarea.style.opacity="0";document.body.appendChild(textarea);textarea.select();document.execCommand("copy");textarea.remove()}
export function WebBuilderScreen({pages,databases,loadPage,onBack,onOpenWhiteboard,onStatus}:{pages:PageWithLock[];databases:WorkspaceDatabase[];loadPage:(id:string)=>Promise<PageBundle>;onBack:()=>void;onOpenWhiteboard:()=>void;onStatus?:(message:string)=>void}){
 const bootstrap=useMemo(()=>{const stored=readWebProjects();const list=stored.length?stored:[createWebProject()];const id=readActiveWebProjectId();return{list,active:normalizeWebProject(list.find(i=>i.id===id)??list[0])}},[]);
 const[projects,setProjects]=useState(bootstrap.list);const[project,setProject]=useState(bootstrap.active);const[tab,setTab]=useState<WebCodeTab>("html");const[panel,setPanel]=useState<WebBuilderPanel>("components");const[bindingKey,setBindingKey]=useState("");const[bindingValue,setBindingValue]=useState("");const[componentName,setComponentName]=useState("");const[responsiveSelector,setResponsiveSelector]=useState("body");const[responsiveDeclaration,setResponsiveDeclaration]=useState("padding:16px");const[responsiveWidth,setResponsiveWidth]=useState(768);const[previewHtml,setPreviewHtml]=useState(()=>compileWebProject(project));const[saveState,setSaveState]=useState<"saved"|"dirty"|"saving">("saved");const[consoleEntries,setConsoleEntries]=useState<WebConsoleEntry[]>([]);const[responsiveView,setResponsiveView]=useState<"split"|"editor"|"preview">("split");const[sidebarCollapsed,setSidebarCollapsed]=useState(false);const[inspectorCollapsed,setInspectorCollapsed]=useState(false);const[consoleCollapsed,setConsoleCollapsed]=useState(false);const[autoPreview,setAutoPreview]=useState(true);const[previewFullscreen,setPreviewFullscreen]=useState(false);const[projectQuery,setProjectQuery]=useState("");const[componentQuery,setComponentQuery]=useState("");const[aiPrompt,setAiPrompt]=useState("");const[auditIssues,setAuditIssues]=useState<WebAuditIssue[]>([]);const[selectedSelector,setSelectedSelector]=useState("body");const[linkType,setLinkType]=useState<"page"|"database">("page");const[linkId,setLinkId]=useState("");const[linkQuery,setLinkQuery]=useState("");const[linkBusyKey,setLinkBusyKey]=useState<string|null>(null);const[linkPanelCollapsed,setLinkPanelCollapsed]=useState(true);const[commandOpen,setCommandOpen]=useState(false);const[commandQuery,setCommandQuery]=useState("");const[inlinePreview,setInlinePreview]=useState(false);
 const previewTimer=useRef<ReturnType<typeof setTimeout>|null>(null),saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),historyTimer=useRef<ReturnType<typeof setTimeout>|null>(null),textareaRef=useRef<HTMLTextAreaElement|null>(null);
 const updateProject=(patch:Partial<WebProject>,label="編集")=>{setProject(current=>syncActivePage({...current,...patch,updatedAt:Date.now()}));setSaveState("dirty");if(historyTimer.current)clearTimeout(historyTimer.current);historyTimer.current=setTimeout(()=>setProject(current=>{const history=[...(current.history??[])];const latest=history[0];if(latest&&latest.html===current.html&&latest.css===current.css&&latest.javascript===current.javascript)return current;return{...current,history:[{id:`history:${Date.now()}`,label,html:current.html,css:current.css,javascript:current.javascript,pageId:current.activePageId!,createdAt:Date.now()},...history].slice(0,30)}}),1400)};
 const codeValue=project[tab];const setCodeValue=(value:string)=>updateProject({[tab]:value}as Partial<WebProject>,`${codeLabel[tab]}編集`);const refreshPreview=()=>{setConsoleEntries([]);setPreviewHtml(compileWebProject(project))};
 useEffect(()=>{if(!autoPreview)return;if(previewTimer.current)clearTimeout(previewTimer.current);previewTimer.current=setTimeout(refreshPreview,350);return()=>{if(previewTimer.current)clearTimeout(previewTimer.current)}},[project.html,project.css,project.javascript,project.theme,project.title,project.variables,project.bindings,project.cmsCollections,project.sharedComponents,project.responsiveRules,project.localFileSources,autoPreview]);
 useEffect(()=>{if(saveState!=="dirty")return;if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{setSaveState("saving");setProjects(saveWebProject(project));setSaveState("saved")},1100);return()=>{if(saveTimer.current)clearTimeout(saveTimer.current)}},[project,saveState]);
 useEffect(()=>{const listener=(event:MessageEvent)=>{const d=event.data;if(!d||d.source!=="local-notion-web-preview")return;setConsoleEntries(items=>[...items.slice(-199),{id:`c:${Date.now()}:${Math.random()}`,level:d.level==="warn"?"warn":d.level==="error"?"error":"log",message:String(d.message??""),createdAt:Date.now()}])};window.addEventListener("message",listener);return()=>window.removeEventListener("message",listener)},[]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="s"){e.preventDefault();setProjects(saveWebProject(project));setSaveState("saved");onStatus?.("Webプロジェクトを保存しました")}if((e.metaKey||e.ctrlKey)&&e.key==="Enter"){e.preventDefault();refreshPreview()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setCommandOpen(v=>!v)}if(e.key==="Escape"){if(commandOpen)setCommandOpen(false);else if(previewFullscreen)setPreviewFullscreen(false)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[project,previewFullscreen,commandOpen]);
 const filteredProjects=useMemo(()=>{const q=projectQuery.trim().toLowerCase();return q?projects.filter(i=>i.title.toLowerCase().includes(q)):projects},[projects,projectQuery]);const navigatorNodes=useMemo(()=>parseNavigator(project.html),[project.html]);const components=useMemo(()=>{const q=componentQuery.trim().toLowerCase();const sorted=[...WEB_COMPONENTS].sort((a,b)=>Number((project.favoriteComponentIds??[]).includes(b.id))-Number((project.favoriteComponentIds??[]).includes(a.id)));return q?sorted.filter(c=>`${c.title}${c.category}`.toLowerCase().includes(q)):sorted},[componentQuery,project.favoriteComponentIds]);const score=qualityScore(auditIssues);const suggestions=useMemo(()=>designSuggestions(project),[project.html,project.css]);
 const selectProject=(next:WebProject)=>{setProject(normalizeWebProject(next));setActiveWebProjectId(next.id);setConsoleEntries([]);setAuditIssues([]);setSaveState("saved")};const createFromTemplate=(id:string)=>{const next=createWebProject(id);setProjects([next,...projects]);selectProject(next);saveWebProject(next)};const removeCurrent=()=>{if(!confirm(`「${project.title}」を削除しますか？`))return;const next=deleteWebProject(project.id),fallback=next[0]??createWebProject();if(!next.length)saveWebProject(fallback);setProjects(next.length?next:[fallback]);selectProject(fallback)};
 const insertComponent=(id:string)=>{const c=WEB_COMPONENTS.find(x=>x.id===id);if(!c)return;updateProject({html:`${project.html.trim()}\n\n<!-- WB-COMPONENT:${c.id} -->\n${c.html}`.trim(),css:c.css&&!project.css.includes(c.css)?`${project.css.trim()}\n\n${c.css}`.trim():project.css},`${c.title}を追加`);setTab("html");onStatus?.(`${c.title}を追加しました`)};
 const addPage=()=>{const title=prompt("ページ名","新しいページ")?.trim();if(!title)return;const slug=(prompt("ファイル名","page")||"page").replace(/[^a-zA-Z0-9-_]/g,"-");const now=Date.now(),page:WebPage={id:`page:${now}`,title,slug,html:`<main class="wb-section"><h1>${escapeHtml(title)}</h1></main>`,createdAt:now,updatedAt:now};updateProject({pages:[...(project.pages??[]),page]},"ページ追加");setProject(current=>switchWebPage(current,page.id))};
 const removePage=(page:WebPage)=>{if((project.pages?.length??0)<=1)return onStatus?.("最後のページは削除できません");if(!confirm(`「${page.title}」を削除しますか？`))return;const next=project.pages!.filter(p=>p.id!==page.id);const active=page.id===project.activePageId?next[0]:project.pages!.find(p=>p.id===project.activePageId)!;updateProject({pages:next,activePageId:active.id,html:active.html},"ページ削除")};
 const uploadAsset=(file:File)=>{if(file.size>2_000_000)return onStatus?.("アセットは1ファイル2MB以下にしてください");const reader=new FileReader();reader.onload=()=>{const asset={id:`asset:${Date.now()}`,name:file.name,type:file.type,dataUrl:String(reader.result),size:file.size,createdAt:Date.now()};updateProject({assets:[asset,...(project.assets??[])].slice(0,40)},"アセット追加")};reader.readAsDataURL(file)};
 const addLink=async()=>{if(!linkId)return;let link:WebProjectLink|null=null;if(linkType==="page"){const page=pages.find(i=>i.id===linkId);if(!page)return;const b=await loadPage(page.id);link={kind:"page",id:page.id,title:page.title,snapshot:`<section class="linked-page" data-source-id="${escapeHtml(page.id)}"><h2>${escapeHtml(page.title)}</h2><div>${escapeHtml(b.markdown.trim()).replace(/\n/g,"<br>")}</div></section>`,updatedAt:page.updatedAt}}else{const db=databases.find(i=>i.id===linkId);if(!db)return;link={kind:"database",id:db.id,title:db.title,snapshot:databaseSnapshot(db),updatedAt:db.updatedAt}}if(project.links.some(i=>i.kind===link!.kind&&i.id===link!.id))return onStatus?.("すでに連携済みです");updateProject({links:[...project.links,link],html:`${project.html.trim()}\n\n${wrapLinkedSnapshot(link)}`.trim()},"外部データ挿入");setLinkId("");setLinkQuery("")};
 const linkCandidates=useMemo(()=>{const source=linkType==="page"?pages:databases,q=linkQuery.trim().toLowerCase();return(q?source.filter(i=>i.title.toLowerCase().includes(q)):source).slice(0,200)},[linkType,linkQuery,pages,databases]);
 const refreshLink=async(link:WebProjectLink)=>{const key=`${link.kind}:${link.id}`;setLinkBusyKey(key);try{let next=link;if(link.kind==="page"){const b=await loadPage(link.id);next={...link,title:b.meta.title,snapshot:`<section class="linked-page" data-source-id="${escapeHtml(link.id)}"><h2>${escapeHtml(b.meta.title)}</h2><div>${escapeHtml(b.markdown.trim()).replace(/\n/g,"<br>")}</div></section>`,updatedAt:b.meta.updatedAt}}else{const db=databases.find(i=>i.id===link.id);if(!db)return;next={...link,title:db.title,snapshot:databaseSnapshot(db),updatedAt:db.updatedAt}}updateProject({html:replaceLinkedSnapshot(project.html,link,next),links:project.links.map(i=>i.kind===link.kind&&i.id===link.id?next:i)},"連携更新")}finally{setLinkBusyKey(null)}};
 const isEditorPreviewFocus=sidebarCollapsed&&inspectorCollapsed;
 const renderInspector=()=>{
  if(panel==="components")return <><input value={componentQuery} onChange={e=>setComponentQuery(e.target.value)} placeholder="コンポーネントを検索"/><div className="wb-component-grid">{components.map(c=>{const favorite=(project.favoriteComponentIds??[]).includes(c.id);return <article className={`wb-component-card${favorite?" is-favorite":""}`} key={c.id}><button className="wb-component-insert" onClick={()=>insertComponent(c.id)} title={`${c.title}を挿入`}><b aria-hidden="true">{c.icon}</b><span>{c.title}</span><small>{c.category}</small></button><button className="wb-favorite" aria-label={favorite?`${c.title}をお気に入りから外す`:`${c.title}をお気に入りに追加`} title={favorite?"お気に入り解除":"お気に入り"} onClick={()=>updateProject({favoriteComponentIds:favorite?project.favoriteComponentIds?.filter(id=>id!==c.id):[...(project.favoriteComponentIds??[]),c.id]},"お気に入り変更")}>{favorite?"★":"☆"}</button></article>})}</div><hr/><h4>共有コンポーネント</h4><input value={componentName} onChange={e=>setComponentName(e.target.value)} placeholder="例：company-header"/><button onClick={()=>{if(!componentName.trim())return;const html=prompt("共有するHTML",project.html.slice(0,500))??"";if(!html)return;updateProject({sharedComponents:[...(project.sharedComponents??[]),makeSharedComponent(componentName,html)]},"共有部品追加");setComponentName("")}}>現在の部品を保存</button><div className="wb-compact-list">{project.sharedComponents?.map(item=><article key={item.id}><b>{item.name}</b><code>{`<ln-component name="${item.name}"></ln-component>`}</code><button onClick={()=>updateProject({html:`${project.html}\n<ln-component name="${item.name}"></ln-component>`},"共有部品挿入")}>挿入</button><button onClick={()=>updateProject({sharedComponents:project.sharedComponents?.filter(x=>x.id!==item.id)},"共有部品削除")}>削除</button></article>)}</div></>;
  if(panel==="navigator")return <><div className="wb-visual-dom-summary"><span>{navigatorNodes.length}要素</span><span>{project.bindings?.length??0}バインド</span><span>{project.responsiveRules?.length??0}規則</span></div><div className="wb-nav-tree">{navigatorNodes.map(n=><button key={n.id} onClick={()=>{setTab("html");textareaRef.current?.focus();textareaRef.current?.setSelectionRange(n.index,n.index+n.tag.length+1)}}><code>{n.tag}</code><span>{n.title}</span></button>)}</div></>;
  if(panel==="properties")return <><label>対象セレクター<input value={selectedSelector} onChange={e=>setSelectedSelector(e.target.value)}/></label><label>文字サイズ<input type="number" defaultValue={16} onBlur={e=>updateProject({css:`${project.css}\n${selectorForTag(selectedSelector)}{font-size:${e.currentTarget.value}px}`},"文字サイズ変更")}/></label><label>余白<input type="number" defaultValue={16} onBlur={e=>updateProject({css:`${project.css}\n${selectorForTag(selectedSelector)}{padding:${e.currentTarget.value}px}`},"余白変更")}/></label><label>角丸<input type="number" defaultValue={12} onBlur={e=>updateProject({css:`${project.css}\n${selectorForTag(selectedSelector)}{border-radius:${e.currentTarget.value}px}`},"角丸変更")}/></label><button onClick={()=>updateProject({css:`${project.css}\n${selectorForTag(selectedSelector)}{transition:transform .2s ease,opacity .2s ease}${selectorForTag(selectedSelector)}:hover{transform:translateY(-3px)}`},"アニメーション追加")}>ホバーアニメーション追加</button><button onClick={()=>updateProject(optimizeLayout(project),"レイアウト自動最適化")}>AIレイアウト最適化</button></>;
  if(panel==="theme")return <div className="wb-theme-form">{(["primary","secondary","background","text"]as const).map(k=><label key={k}>{k}<input type="color" value={project.theme?.[k]??DEFAULT_THEME[k]} onChange={e=>updateProject({theme:{...project.theme!,[k]:e.target.value}},"テーマ変更")}/></label>)}<label>角丸<input type="range" min="0" max="32" value={project.theme?.radius??12} onChange={e=>updateProject({theme:{...project.theme!,radius:Number(e.target.value)}},"テーマ変更")}/></label><label>間隔<input type="range" min="4" max="40" value={project.theme?.spacing??16} onChange={e=>updateProject({theme:{...project.theme!,spacing:Number(e.target.value)}},"テーマ変更")}/></label><button onClick={()=>updateProject({theme:{...project.theme!,primary:"#173f7a",secondary:"#b38b2d",background:"#f7f9fc",text:"#172033"}},"行政向け配色")}>行政向け配色</button><button onClick={()=>updateProject({theme:{...project.theme!,primary:"#111827",secondary:"#6b7280",background:"#0b1020",text:"#f8fafc"}},"ダーク配色")}>ダーク配色</button></div>;
  if(panel==="assets")return <><label className="wb-upload">＋ 素材を追加<input type="file" accept="image/*,.svg" onChange={e=>{const f=e.target.files?.[0];if(f)uploadAsset(f);e.currentTarget.value=""}}/></label><div className="wb-assets">{project.assets?.map(a=><article key={a.id}><img src={a.dataUrl}/><span>{a.name}</span><button onClick={()=>{void copyText(a.dataUrl);onStatus?.("素材URLをコピーしました")}}>URLコピー</button><button onClick={()=>updateProject({assets:project.assets?.filter(x=>x.id!==a.id)},"素材削除")}>削除</button></article>)}</div></>;
  if(panel==="pages")return <><button onClick={addPage}>＋ ページ追加</button><div className="wb-page-list">{project.pages?.map(p=><article className={p.id===project.activePageId?"active":""} key={p.id}><button onClick={()=>setProject(current=>switchWebPage(current,p.id))}><b>{p.title}</b><small>{p.slug}.html</small></button><button onClick={()=>removePage(p)}>×</button></article>)}</div></>;
  if(panel==="data")return <><h4>ローカルファイル</h4><p>JSON・CSV・HTMLをプロジェクト内のデータソースとして読み込みます。</p><label className="wb-upload">＋ ファイルを読み込む<input type="file" accept=".json,.csv,.html,.htm,application/json,text/csv,text/html" onChange={async e=>{const file=e.target.files?.[0];e.currentTarget.value="";if(!file)return;try{const source=await readLocalWebFile(file);updateProject(addLocalSource(project,source),"ローカルファイル読込");onStatus?.(`${file.name}を読み込みました`)}catch(error){onStatus?.(error instanceof Error?error.message:"ファイルを読み込めませんでした")}}}/></label><div className="wb-local-source-list">{project.localFileSources?.map(source=>{const keys=localSourceBindingKeys(source);return <article key={source.id}><div className="wb-local-source-title"><b>{source.fileName}</b><small>{source.format.toUpperCase()}・{source.records.length||1}件・{Math.ceil(source.size/1024)}KB</small></div><code>{localSourceTag(source)}</code>{keys.length>0&&<small className="wb-local-source-hint">例：{`{{${keys[0].key}}}`}</small>}<div className="wb-local-source-actions"><button onClick={()=>updateProject({html:`${project.html}\n${localSourceTag(source)}`},"ローカルソース挿入")}>ページへ挿入</button>{keys.length>0&&<button onClick={()=>{void copyText(`{{${keys[0].key}}}`);onStatus?.("参照キーをコピーしました")}}>参照キー</button>}<button onClick={()=>updateProject({localFileSources:project.localFileSources?.filter(item=>item.id!==source.id)},"ローカルソース削除")}>削除</button></div></article>})}</div><h4>Live Binding / Variables</h4><input value={bindingKey} onChange={e=>setBindingKey(e.target.value)} placeholder="キー 例：officeName"/><textarea value={bindingValue} onChange={e=>setBindingValue(e.target.value)} placeholder="表示する値"/><button onClick={()=>{if(!bindingKey.trim())return;updateProject({bindings:[...(project.bindings??[]),makeBinding(bindingKey,bindingValue)]},"バインディング追加");setBindingKey("");setBindingValue("")}}>追加</button><div className="wb-compact-list">{project.bindings?.map(item=><article key={item.id}><code>{`{{${item.key}}}`}</code><span>{item.value}</span><button onClick={()=>updateProject({bindings:project.bindings?.filter(x=>x.id!==item.id)},"バインディング削除")}>削除</button></article>)}</div><h4>CMS</h4><button onClick={()=>{const name=prompt("CMS名","news")?.trim();if(!name)return;const collection={id:`cms:${Date.now()}`,name,layout:"grid" as const,limit:20,items:[{id:`item:${Date.now()}`,title:"お知らせ",summary:"CMSから表示される内容です",date:new Date().toLocaleDateString("ja-JP"),published:true}]};updateProject({cmsCollections:[...(project.cmsCollections??[]),collection],html:`${project.html}\n<ln-cms name="${name}"></ln-cms>`},"CMS追加")}}>ニュースCMSを追加</button><h4>フォーム</h4><button onClick={()=>updateProject({html:`${project.html}\n<form data-ln-form><label>お名前<input name="name" required></label><label>メール<input name="email" type="email" required></label><button type="submit">送信</button><p data-ln-form-message></p></form>`},"フォーム追加")}>問い合わせフォームを追加</button></>;
  if(panel==="responsive")return <><p>端末ごとのCSSを共通ルールとして保存します。</p><label>最大幅<input type="number" value={responsiveWidth} onChange={e=>setResponsiveWidth(Number(e.target.value))}/></label><label>セレクター<input value={responsiveSelector} onChange={e=>setResponsiveSelector(e.target.value)}/></label><label>CSS<textarea value={responsiveDeclaration} onChange={e=>setResponsiveDeclaration(e.target.value)}/></label><button onClick={()=>updateProject({responsiveRules:[...(project.responsiveRules??[]),{id:`rule:${Date.now()}`,maxWidth:responsiveWidth,selector:responsiveSelector,declarations:responsiveDeclaration}]},"レスポンシブ規則追加")}>規則を追加</button><div className="wb-compact-list">{project.responsiveRules?.map(rule=><article key={rule.id}><b>≤ {rule.maxWidth}px</b><code>{rule.selector}{`{${rule.declarations}}`}</code><button onClick={()=>updateProject({responsiveRules:project.responsiveRules?.filter(x=>x.id!==rule.id)},"規則削除")}>削除</button></article>)}</div></>;
  if(panel==="quality")return <><button onClick={()=>setAuditIssues(auditWebProject(project))}>品質チェックを実行</button><button onClick={()=>updateProject(optimizeLayout(project),"品質自動修正")}>安全な項目を自動修正</button>{auditIssues.length>0&&<div className="wb-score"><strong>{score}</strong><span>/ 100</span></div>}<div className="wb-issues">{auditIssues.map(i=><article className={`is-${i.severity}`} key={i.id}><b>{i.title}</b><p>{i.detail}</p>{i.fix&&<small>{i.fix}</small>}</article>)}</div></>;
  if(panel==="history"){const previous=project.history?.[0];const diff=compareVersions(project,previous);return <><div className="wb-diff-summary"><b>現在との差分</b><span>HTML {diff.html}</span><span>CSS {diff.css}</span><span>JS {diff.javascript}</span></div><button onClick={()=>updateProject({css:autoLayoutCss(project.css)},"自動レイアウト")}>Smart Auto Layout</button><div className="wb-history">{project.history?.map(h=><button key={h.id} onClick={()=>{if(confirm("この履歴へ戻しますか？"))updateProject({html:h.html,css:h.css,javascript:h.javascript},"履歴復元")}}><b>{h.label}</b><small>{new Date(h.createdAt).toLocaleString("ja-JP")}</small></button>)}</div></>}
  if(panel==="templates")return <><h4>ユーザーテンプレート</h4><button onClick={()=>{const name=prompt("テンプレート名",project.title);if(!name)return;updateProject({userTemplates:[createUserTemplate(project,name),...(project.userTemplates??[])]},"テンプレート保存")}}>現在のページを保存</button><div className="wb-compact-list">{project.userTemplates?.map(t=><article key={t.id}><b>{t.name}</b><small>{new Date(t.createdAt).toLocaleString("ja-JP")}</small><button onClick={()=>updateProject(applyUserTemplate(project,t),"テンプレート適用")}>適用</button><button onClick={()=>updateProject({userTemplates:project.userTemplates?.filter(x=>x.id!==t.id)},"テンプレート削除")}>削除</button></article>)}</div></>;
  if(panel==="plugins")return <><h4>プラグイン</h4><p>必要な機能だけ有効化し、Runtimeで一度だけ合成します。</p><div className="wb-compact-list">{BUILTIN_PLUGINS.map(base=>{const current=project.plugins?.find(p=>p.id===base.id)??base;return <article key={base.id}><b>{base.name}</b><label><input type="checkbox" checked={current.enabled} onChange={e=>updateProject({plugins:[...(project.plugins??[]).filter(p=>p.id!==base.id),{...base,enabled:e.target.checked}]},"プラグイン変更")}/>有効</label>{base.html&&<button onClick={()=>updateProject({html:`${project.html}
${base.html}`},"プラグイン部品挿入")}>部品を挿入</button>}</article>})}</div><h4>モーション</h4><button onClick={()=>updateProject({css:motionCss(project.css,"reveal")},"Reveal追加")}>Reveal</button><button onClick={()=>updateProject({css:motionCss(project.css,"float")},"Float追加")}>Float</button><button onClick={()=>updateProject({css:motionCss(project.css,"pulse")},"Pulse追加")}>Pulse</button></>;
  if(panel==="publish")return <><h4>公開</h4><select value={project.deploy?.provider??"manual"} onChange={e=>updateProject({deploy:{...project.deploy!,provider:e.target.value as NonNullable<WebProject["deploy"]>["provider"]}},"公開先変更")}><option value="manual">手動ZIP</option><option value="github-pages">GitHub Pages</option><option value="netlify">Netlify</option><option value="vercel">Vercel</option><option value="cloudflare">Cloudflare Pages</option></select><button onClick={()=>exportProjectZip(project)}>公開用ZIPを書き出す</button><button onClick={()=>{void copyText(JSON.stringify(buildDeployGuide(project),null,2));onStatus?.("公開手順をコピーしました")}}>公開手順をコピー</button><p>認証情報をアプリ内へ保存せず、静的ファイルと公開ガイドを生成します。</p></>;
  return <><textarea value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="例：ヒーローとFAQを追加して、余白を広くする"/><button onClick={()=>{if(!aiPrompt.trim())return;updateProject(applyDesignerPrompt(project,aiPrompt),"AIデザイン");setAiPrompt("")}}>AIデザインを適用</button><button onClick={()=>updateProject(optimizeLayout(project),"AIレイアウト最適化")}>レイアウトを自動最適化</button><div className="wb-ai-suggestions"><h4>AIインスペクター</h4>{suggestions.map(s=><p key={s}>✦ {s}</p>)}</div></>;
 };
 return <div className="web-builder-screen wb-v778"><header className="web-builder-header"><button onClick={onBack}>← 戻る</button><button className="web-icon-button" onClick={()=>setSidebarCollapsed(v=>!v)}>☰</button><button className="web-icon-button" title="コマンドパレット (⌘K)" onClick={()=>setCommandOpen(true)}>⌘K</button><input value={project.title} onChange={e=>updateProject({title:e.target.value},"タイトル変更")}/><span className={`web-save-state is-${saveState}`}>{saveState==="saved"?"保存済み":saveState==="saving"?"保存中…":"未保存"}</span><div className="wb-responsive-view-switch" role="group" aria-label="作業画面の表示"><button className={responsiveView==="editor"?"active":""} onClick={()=>setResponsiveView("editor")}>編集</button><button className={responsiveView==="split"?"active":""} onClick={()=>setResponsiveView("split")}>分割</button><button className={responsiveView==="preview"?"active":""} onClick={()=>setResponsiveView("preview")}>サイト</button></div><div className="web-builder-actions"><button onClick={()=>exportSingleHtml(project)}>HTML</button><button onClick={()=>exportProjectZip(project)}>ZIP</button><button onClick={()=>{saveWebProject(project);queueWebProjectForWhiteboard(project);onOpenWhiteboard()}}>▧ ホワイトボード</button></div></header>
 <div className={`web-builder-layout is-responsive-${responsiveView}${sidebarCollapsed?" is-sidebar-collapsed":""}${inspectorCollapsed?" is-inspector-collapsed":""}${consoleCollapsed?" is-console-collapsed":""}`}><aside className="web-project-sidebar"><h2>Web Builder</h2><input value={projectQuery} onChange={e=>setProjectQuery(e.target.value)} placeholder="プロジェクトを検索"/><select onChange={e=>{if(e.target.value)createFromTemplate(e.target.value);e.currentTarget.value=""}} defaultValue=""><option value="" disabled>テンプレートから作成</option>{WEB_TEMPLATES.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select><div className="web-project-list">{filteredProjects.map(i=><button key={i.id} className={i.id===project.id?"active":""} onClick={()=>selectProject(i)}><strong>{i.title}</strong><small>{new Date(i.updatedAt).toLocaleString("ja-JP")}</small></button>)}</div><button className="danger" onClick={removeCurrent}>プロジェクトを削除</button></aside>
 <aside className="wb-inspector"><nav>{(Object.keys(PANEL_LABEL)as WebBuilderPanel[]).map(p=><button title={PANEL_LABEL[p]} className={panel===p?"active":""} key={p} onClick={()=>{setPanel(p);setInspectorCollapsed(false)}}>{PANEL_LABEL[p].slice(0,2)}</button>)}</nav><div className="wb-inspector-body"><header><b>{PANEL_LABEL[panel]}</b><button onClick={()=>setInspectorCollapsed(true)}>‹</button></header>{renderInspector()}</div></aside>
 <section className={`web-code-pane${linkPanelCollapsed?" is-link-panel-collapsed":""}`}><div className="web-code-tabs"><div>{(["html","css","javascript"]as WebCodeTab[]).map(i=><button className={tab===i?"active":""} key={i} onClick={()=>setTab(i)}>{codeLabel[i]}</button>)}</div><div className="web-code-tools"><button onClick={()=>void copyText(codeValue)}>コピー</button><button onClick={()=>setLinkPanelCollapsed(v=>!v)}>{linkPanelCollapsed?"データ挿入":"閉じる"}</button></div></div><textarea ref={textareaRef} spellCheck={false} value={codeValue} onChange={e=>setCodeValue(e.target.value)} onKeyDown={e=>{if(e.key!=="Tab")return;e.preventDefault();const t=e.currentTarget,s=t.selectionStart,end=t.selectionEnd;setCodeValue(`${codeValue.slice(0,s)}  ${codeValue.slice(end)}`);requestAnimationFrame(()=>t.selectionStart=t.selectionEnd=s+2)}}/><section className="web-link-panel"><header><div><strong>ページ・DB挿入</strong><small>静的スナップショットとして管理</small></div><span>{project.links.length}件</span></header><div className="web-link-insert-row"><select value={linkType} onChange={e=>{setLinkType(e.target.value as"page"|"database");setLinkId("")}}><option value="page">ページ</option><option value="database">データベース</option></select><input value={linkQuery} onChange={e=>setLinkQuery(e.target.value)} placeholder="検索"/><select value={linkId} onChange={e=>setLinkId(e.target.value)}><option value="">選択</option>{linkCandidates.map(i=><option value={i.id} key={i.id}>{i.title}</option>)}</select><button onClick={()=>void addLink()} disabled={!linkId}>＋ 挿入</button></div><ul className="web-linked-items">{project.links.map(link=>{const busy=linkBusyKey===`${link.kind}:${link.id}`;return <li key={`${link.kind}:${link.id}`}><span><b>{link.title}</b><small>{link.kind}</small></span><div><button onClick={()=>void refreshLink(link)} disabled={busy}>{busy?"更新中":"更新"}</button><button onClick={()=>updateProject({html:removeLinkedSnapshot(project.html,link),links:project.links.filter(i=>i!==link)},"連携削除")}>削除</button></div></li>})}</ul></section></section>
 <section className={`web-preview-pane${previewFullscreen?" is-fullscreen":""}`}><div className="web-preview-toolbar"><div>{(["desktop","tablet","mobile","iphone","ipad","macbook","wide"]as WebPreviewDevice[]).map(d=><button key={d} className={project.device===d?"active":""} onClick={()=>updateProject({device:d},"端末変更")}>{d}</button>)}</div><div className="web-preview-controls"><label><input type="checkbox" checked={autoPreview} onChange={e=>setAutoPreview(e.target.checked)}/>自動</label><button onClick={refreshPreview}>↻</button><button className={inlinePreview?"active":""} onClick={()=>setInlinePreview(v=>!v)}>直接編集</button><button onClick={()=>setPreviewFullscreen(v=>!v)}>{previewFullscreen?"縮小":"全画面"}</button><span>{htmlToText(project.html).length}文字</span></div></div><div className="web-preview-stage"><iframe key={`preview:${inlinePreview}`} title="Webプレビュー" sandbox="allow-scripts allow-forms" srcDoc={previewHtml} onLoad={e=>{const doc=e.currentTarget.contentDocument;if(!doc)return;doc.body.contentEditable=inlinePreview?"true":"false";doc.body.oninput=inlinePreview?()=>{updateProject({html:doc.body.innerHTML},"プレビュー直接編集")}:null}} scrolling="yes" style={{width:isEditorPreviewFocus&&(project.device==="desktop"||project.device==="wide")?"100%":DEVICE_WIDTH[project.device]?`${DEVICE_WIDTH[project.device]}px`:"100%"}}/></div><div className="web-console"><header><strong>Console</strong><div><button onClick={()=>setConsoleCollapsed(v=>!v)}>{consoleCollapsed?"開く":"閉じる"}</button><button onClick={()=>setConsoleEntries([])}>クリア</button></div></header><div>{consoleEntries.length?consoleEntries.map(e=><p className={`is-${e.level}`} key={e.id}><span>{e.level}</span>{e.message}</p>):<p className="empty">ログはありません</p>}</div></div></section></div>{commandOpen&&<div className="wb-command-backdrop" onMouseDown={()=>setCommandOpen(false)}><section className="wb-command-palette" onMouseDown={e=>e.stopPropagation()}><input autoFocus value={commandQuery} onChange={e=>setCommandQuery(e.target.value)} placeholder="コマンドを検索…"/><div>{[
 {id:"save",label:"保存",run:()=>{setProjects(saveWebProject(project));setSaveState("saved")}},
 {id:"preview",label:"プレビュー更新",run:refreshPreview},
 {id:"layout",label:"Smart Auto Layout",run:()=>updateProject({css:autoLayoutCss(project.css)},"自動レイアウト")},
 {id:"template",label:"テンプレートとして保存",run:()=>{const name=prompt("テンプレート名",project.title);if(name)updateProject({userTemplates:[createUserTemplate(project,name),...(project.userTemplates??[])]},"テンプレート保存")}},
 {id:"export",label:"ZIPを書き出す",run:()=>exportProjectZip(project)},
 {id:"components",label:"コンポーネントを開く",run:()=>{setPanel("components");setInspectorCollapsed(false)}},
 {id:"navigator",label:"Visual DOMを開く",run:()=>{setPanel("navigator");setInspectorCollapsed(false)}},
 ].filter(c=>c.label.toLowerCase().includes(commandQuery.toLowerCase())).map(c=><button key={c.id} onClick={()=>{c.run();setCommandOpen(false);setCommandQuery("")}}>{c.label}</button>)}</div><small>⌘Kで開閉・Escで閉じる</small></section></div>}</div>
}
