import type { SmartFaqSearchRecord } from './japaneseFaqSearch';

const now = '2026-06-11T00:00:00.000+09:00';

export const SAMPLE_SMART_FAQ_RECORDS: SmartFaqSearchRecord[] = [
  {
    id: 'sample_faq_missed_deadline',
    question: '申請期限が過ぎてしまった場合はどうすればよいですか？',
    answer: '申請期限が過ぎた場合は、まず対象手続き名、提出期限、提出先、遅延理由を確認してください。期限後の受付可否は手続きごとに異なるため、自己判断で再提出せず、所属または担当部署へ相談します。必要に応じて、理由書、再申請書、所属長確認などを求められる場合があります。',
    category: '申請・手続き',
    tags: ['申請期限', '締切', '提出期限', '期限後', '遅延', '手続き'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：申請・手続き'],
    sourceText: '期限後の申請は、手続き名・期限・提出先・遅延理由を整理し、担当部署へ確認する。',
    intentId: 'missed_deadline',
    intentLabel: '申請期限超過',
    intent: ['missed_deadline', 'application_procedure'],
    domain: '行政手続き',
    domainId: 'application',
    confidence: 95,
    followUpQuestions: ['対象の手続き名は何ですか？', '提出期限はいつでしたか？', '担当部署や所属には連絡済みですか？'],
    testQuestions: ['申請期限が過ぎてしまった', '提出期限を過ぎた', '締切に間に合わなかった'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_application_method',
    question: '申請方法を確認したい場合はどうすればよいですか？',
    answer: '申請方法は、電子申請、紙様式、メール提出、所属経由など手続きごとに異なります。確認する順番は、対象手続き名、提出先、提出期限、必要書類、本人確認や押印の要否です。案内文や手引きがある場合は、最新年度の資料を確認してください。',
    category: '申請・手続き',
    tags: ['申請方法', '電子申請', '紙様式', 'メール提出', '所属経由', '必要書類'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：申請・手続き'],
    sourceText: '申請方法は手続きごとに異なる。手続き名、提出先、期限、必要書類を確認する。',
    intentId: 'application_procedure',
    intentLabel: '申請方法確認',
    intent: ['application_procedure'],
    domain: '行政手続き',
    domainId: 'application',
    confidence: 92,
    followUpQuestions: ['どの手続きの申請方法を確認したいですか？', '電子申請と紙提出のどちらを想定していますか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_required_documents',
    question: '必要書類や添付書類を確認したい場合はどうすればよいですか？',
    answer: '必要書類は制度や申請内容によって異なります。まず申請する制度名、対象者、申請理由、提出先を確認してください。本人確認書類、証明書、勤務証明、口座情報、理由書などが必要になることがあります。不足書類があると受付後に差し戻しになる場合があります。',
    category: '申請・手続き',
    tags: ['必要書類', '添付書類', '証明書', '本人確認', '勤務証明', '理由書'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：必要書類'],
    sourceText: '必要書類は制度・申請内容・対象者によって異なる。添付漏れがあると差し戻しになる。',
    intentId: 'required_documents',
    intentLabel: '必要書類確認',
    intent: ['required_documents'],
    domain: '行政手続き',
    domainId: 'application',
    confidence: 90,
    followUpQuestions: ['どの制度の必要書類ですか？', '新規申請ですか、変更申請ですか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_worktime_change',
    question: '勤務時間を変更したい場合はどうすればよいですか？',
    answer: '勤務時間を変更したい場合は、変更希望日、変更理由、変更後の勤務時間、勤務形態への影響を整理してください。一時的な変更か継続的な変更かで扱いが異なります。原則として、事前に所属長または人事担当へ確認し、必要な申請や承認を受けます。',
    category: '勤務条件',
    tags: ['勤務時間', '出勤時間', '退勤時間', 'シフト変更', '勤務形態', '事前承認'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：勤務条件'],
    sourceText: '勤務時間変更は、変更希望日、理由、変更後時間、勤務形態への影響を整理して事前確認する。',
    intentId: 'worktime_change',
    intentLabel: '勤務時間変更',
    intent: ['worktime_change'],
    domain: '人事労務',
    domainId: 'hr',
    confidence: 94,
    followUpQuestions: ['変更は一時的ですか、継続的ですか？', '変更希望日はいつですか？', '所属長には相談済みですか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_annual_leave',
    question: '年休や有休を取得したい場合、またはいつから取得できるか確認したい場合はどうすればよいですか？',
    answer: '年次休暇を取得する場合は、取得希望日、取得時間、勤務予定、残日数を確認し、所定の方法で申請してください。業務に支障が出る可能性がある場合は、事前に所属内で調整してください。時間単位で取得できるかどうかは制度や勤務条件によって異なります。有給休暇・年次休暇をいつから取得できるかは、任用形態、勤務開始日、勤務日数、勤務時間、継続勤務期間により異なるため、雇用通知書や人事担当の案内を確認してください。',
    category: '休暇',
    tags: ['年休', '有休', '有給', '年次休暇', '有給休暇', '付与日', '取得開始', '休暇', '休み'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：休暇'],
    sourceText: '年休取得は希望日、勤務予定、残日数、業務影響を確認する。有給・年休の取得開始時期は任用形態や勤務条件により異なる。',
    intentId: 'leave_vacation',
    intentLabel: '休暇取得・有給取得開始',
    intent: ['leave_vacation', 'leave.paid_start', 'annual_leave'],
    domain: '人事労務',
    domainId: 'hr',
    confidence: 93,
    followUpQuestions: ['取得したい休暇の種類は年休ですか？', '勤務開始日はいつですか？', '週の勤務日数は何日ですか？', '残日数は確認済みですか？'],
    testQuestions: ['有給はいつから取得できますか', '有休はいつから使えますか', '年休を取得したい', '年次休暇はいつから取れますか'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_sick_leave',
    question: '病気や体調不良で休む場合はどうすればよいですか？',
    answer: '病気や体調不良で勤務できない場合は、できるだけ早く所属へ連絡してください。休暇の扱いは、年休、病気休暇、欠勤など状況や任用形態によって異なります。連続して休む場合や診断書が必要な場合があるため、所属または人事担当へ確認します。',
    category: '休暇',
    tags: ['病気休暇', '体調不良', '欠勤', '診断書', '年休', '連絡'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：休暇'],
    sourceText: '体調不良時は早めに所属へ連絡し、休暇区分や必要書類を確認する。',
    intentId: 'leave_vacation',
    intentLabel: '病気休暇・体調不良',
    intent: ['leave_vacation'],
    domain: '人事労務',
    domainId: 'hr',
    confidence: 88,
    followUpQuestions: ['当日中の休みですか？', '連続して休む予定ですか？', '診断書の指示はありますか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_commuting_allowance',
    question: '通勤手当や交通費は支給されますか？',
    answer: '通勤手当や交通費の支給可否は、任用形態、勤務日数、通勤距離、交通手段、支給要件によって異なります。確認する際は、住所、勤務場所、通勤経路、公共交通機関の利用有無、勤務日数を整理してください。変更があった場合は届出が必要です。',
    category: '給与・手当',
    tags: ['通勤手当', '交通費', '定期代', '通勤経路', '勤務日数', '住所変更'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：給与・手当'],
    sourceText: '通勤手当は任用形態、勤務日数、通勤距離、交通手段、支給要件により異なる。',
    intentId: 'allowance_salary',
    intentLabel: '通勤手当確認',
    intent: ['allowance_salary'],
    domain: '人事労務',
    domainId: 'hr',
    confidence: 91,
    followUpQuestions: ['確認したいのは通勤手当ですか？', '通勤経路や勤務日数は分かりますか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_salary_payment',
    question: '給与や報酬の支給日を確認したい場合はどうすればよいですか？',
    answer: '給与や報酬の支給日は、任用形態や支給区分によって異なる場合があります。確認する際は、対象月、任用形態、勤務実績、控除や手当の有無を整理してください。支給額に疑義がある場合は、給与明細と勤務実績を照合して担当部署へ確認します。',
    category: '給与・手当',
    tags: ['給与', '給料', '報酬', '支給日', '給与明細', '勤務実績'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：給与・手当'],
    sourceText: '給与支給日は任用形態や支給区分で異なる。疑義がある場合は明細と勤務実績を確認する。',
    intentId: 'allowance_salary',
    intentLabel: '給与確認',
    intent: ['allowance_salary'],
    domain: '人事労務',
    domainId: 'hr',
    confidence: 87,
    followUpQuestions: ['確認したいのは支給日ですか、支給額ですか？', '対象月はいつですか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_eligibility_requirement',
    question: '制度の対象になるか、要件を確認したい場合はどうすればよいですか？',
    answer: '制度の対象になるか確認する場合は、対象者区分、勤務日数、勤務時間、勤務期間、住所要件、年齢要件、申請期限などを整理してください。要件の一部だけで判断せず、手引きや担当部署の案内に基づいて確認します。',
    category: '利用条件・要件',
    tags: ['対象要件', '条件', '該当', '勤務日数', '勤務時間', '住所要件'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：利用条件'],
    sourceText: '対象要件は対象者区分、勤務日数、勤務時間、勤務期間、住所要件等を総合して確認する。',
    intentId: 'eligibility_requirement',
    intentLabel: '対象要件確認',
    intent: ['eligibility_requirement'],
    domain: '制度確認',
    domainId: 'eligibility',
    confidence: 90,
    followUpQuestions: ['どの制度の対象要件ですか？', '勤務日数や勤務時間は分かりますか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_change_cancel_application',
    question: '申請後に内容を取り消したい場合はどうすればよいですか？',
    answer: '申請を取り消したい場合は、対象手続き名、申請日、申請番号、申請者名、取消理由を整理し、速やかに提出先または担当部署へ連絡してください。手続きの進行状況によっては、通常の取消ではなく変更申請や訂正依頼が必要になる場合があります。すでに受理・審査・決定済みの場合は、システム上で取消できない可能性があるため、担当部署へ確認してください。',
    category: '申請・手続き',
    tags: ['申請取消', '申請後', '取消', '取り消し', '取り下げ', 'キャンセル', '訂正', '変更申請', '申請番号'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：申請取消'],
    sourceText: '申請取消は、手続き名、申請日、申請番号、取消理由を整理し、提出先または担当部署へ確認する。',
    intentId: 'application_cancel',
    intentLabel: '申請取消',
    intent: ['application_cancel', 'application_procedure'],
    domain: '行政手続き',
    domainId: 'application',
    confidence: 96,
    followUpQuestions: ['どの手続きを取り消したいですか？', '申請番号や申請日は分かりますか？', '申請はすでに受理されていますか？', '訂正ではなく完全な取消ですか？'],
    testQuestions: ['申請した後に取り消したい', '申請後にキャンセルしたい', '申請を取り下げたい', '間違えて申請しました'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_after_school_fee',
    question: '放課後児童クラブの費用を確認したい場合はどうすればよいですか？',
    answer: '放課後児童クラブの費用は、自治体、利用区分、利用時間、減免制度、おやつ代や延長利用料の有無によって異なります。確認する際は、対象自治体、学年、利用月、通常利用か長期休業中か、延長利用の有無を整理してください。',
    category: '放課後児童クラブ',
    tags: ['放課後児童クラブ', '学童', '費用', '保育料', '減免', '延長利用'],
    status: 'reviewed',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：放課後児童クラブ'],
    sourceText: '学童の費用は自治体、利用区分、利用時間、減免、延長利用料等で異なる。',
    intentId: 'eligibility_requirement',
    intentLabel: '放課後児童クラブ費用確認',
    intent: ['eligibility_requirement'],
    domain: '子育て支援',
    domainId: 'childcare',
    confidence: 84,
    followUpQuestions: ['対象自治体はどこですか？', '通常利用ですか、長期休業中の利用ですか？', '延長利用はありますか？'],
    suggestedActions: ['月額利用料を確認する', '延長利用料を確認する', '減免制度を確認する', '長期休業期間の追加費用を確認する', '担当課への問い合わせ文を作成する'],
    nextQuestions: ['延長利用料はいくらですか？', '減免制度はありますか？', '夏休みだけ利用できますか？', '兄弟利用の割引はありますか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },

  {
    id: 'sample_faq_paid_leave_start',
    question: '有給休暇・年次休暇はいつから取得できますか？',
    answer: '有給休暇または年次休暇をいつから取得できるかは、任用形態、勤務開始日、勤務日数、勤務時間、継続勤務期間によって異なります。一般的には、一定期間継続して勤務し、所定の勤務条件を満たした場合に付与されます。会計年度任用職員などの場合は、任用条件や勤務日数により付与日数や取得可能時期が異なるため、雇用通知書、休暇制度の案内、所属または人事担当の説明を確認してください。',
    category: '休暇',
    tags: ['有給', '有休', '年休', '年次休暇', '有給休暇', '付与日', '取得開始'],
    status: 'approved',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：休暇'],
    sourceText: '年次有給休暇は任用形態、勤務開始日、勤務日数、勤務時間、継続勤務期間によって付与時期が異なる。',
    intentId: 'leave.paid_start',
    intentLabel: '有給・年休の取得開始',
    intent: ['leave.paid_start', 'annual_leave'],
    domain: '休暇',
    domainId: 'leave',
    confidence: 95,
    followUpQuestions: ['勤務開始日はいつですか？', '任用形態は常勤ですか、会計年度任用職員ですか？', '週の勤務日数は何日ですか？', '1日の勤務時間は何時間ですか？'],
    testQuestions: ['有給はいつから取得できますか', '有休はいつから使えますか', '年休はいつ付与されますか', '入職後いつから有給が使えますか'],
    suggestedActions: ['取得条件を確認する', '付与日を確認する', '残日数を確認する', '休暇の申請方法を確認する'],
    nextQuestions: ['時間単位で休暇を取れますか？', '会計年度任用職員の年休はいつからですか？', '年休の残日数はどこで確認できますか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
  {
    id: 'sample_faq_lgwan_usage',
    question: 'LGWAN回線や庁内ネットワークの利用で注意することは何ですか？',
    answer: 'LGWAN回線や庁内ネットワークを利用する場合は、所属の情報セキュリティルールに従ってください。外部サービス、USB、個人端末、クラウド同期、ファイル持ち出しは制限される場合があります。判断に迷う場合は、情報政策担当または所属の管理者へ確認します。',
    category: '情報システム',
    tags: ['LGWAN', '庁内ネットワーク', '情報セキュリティ', '外部サービス', 'USB', 'クラウド'],
    status: 'reviewed',
    sourceType: 'faq',
    sourceTitles: ['サンプルFAQ：情報システム'],
    sourceText: 'LGWANや庁内ネットワークの利用は情報セキュリティルールに従う。外部サービス等は確認が必要。',
    intentId: 'system.lgwan_external_service',
    intentLabel: '庁内ネットワーク利用確認',
    intent: ['system.lgwan_external_service', 'it_security'],
    domain: '情報システム',
    domainId: 'it',
    confidence: 80,
    followUpQuestions: ['何をLGWAN環境で使いたいですか？', '外部サービスやUSB利用を想定していますか？'],
    createdAt: now,
    updatedAt: now,
    updatedBy: 'sample-seed',
  },
];

export function cloneSampleSmartFaqRecords(): SmartFaqSearchRecord[] {
  const freshNow = new Date().toISOString();
  return SAMPLE_SMART_FAQ_RECORDS.map((item) => ({
    ...item,
    tags: Array.isArray(item.tags) ? [...item.tags] : [],
    sourceTitles: Array.isArray(item.sourceTitles) ? [...item.sourceTitles] : [],
    intent: Array.isArray(item.intent) ? [...item.intent] : item.intent,
    intentIds: Array.isArray(item.intentIds) ? [...item.intentIds] : item.intentIds,
    followUpQuestions: Array.isArray((item as any).followUpQuestions) ? [...(item as any).followUpQuestions] : undefined,
    createdAt: item.createdAt || freshNow,
    updatedAt: freshNow,
  }));
}
