export type WebComponentDefinition={id:string;category:string;title:string;icon:string;html:string;css?:string};
export const WEB_COMPONENTS:WebComponentDefinition[]=[
{id:"heading",category:"基本",title:"見出し",icon:"H",html:'<section class="wb-section"><h2 data-wb-editable>セクション見出し</h2><p>説明文を入力してください。</p></section>'},
{id:"button",category:"基本",title:"ボタン",icon:"▣",html:'<a class="wb-button" href="#">お問い合わせ</a>',css:'.wb-button{display:inline-flex;align-items:center;justify-content:center;padding:.75rem 1.15rem;border-radius:var(--wb-radius);background:var(--wb-primary);color:#fff;text-decoration:none;font-weight:700}'},
{id:"hero",category:"セクション",title:"ヒーロー",icon:"✦",html:'<section class="wb-hero"><p class="wb-eyebrow">WELCOME</p><h1>伝わるWebサイトを、もっと簡単に。</h1><p>ここにサービスの価値を簡潔に説明します。</p><a class="wb-button" href="#details">詳しく見る</a></section>',css:'.wb-hero{min-height:56vh;display:grid;align-content:center;gap:1rem;padding:clamp(2rem,8vw,7rem);background:linear-gradient(135deg,color-mix(in srgb,var(--wb-primary) 12%,white),white)}.wb-hero h1{font-size:clamp(2.2rem,6vw,5rem);line-height:1.05;max-width:12ch;margin:0}.wb-eyebrow{font-weight:800;color:var(--wb-primary);letter-spacing:.14em}'},
{id:"card-grid",category:"レイアウト",title:"カードグリッド",icon:"▦",html:'<section class="wb-section"><div class="wb-grid"><article class="wb-card"><h3>カード1</h3><p>内容を入力します。</p></article><article class="wb-card"><h3>カード2</h3><p>内容を入力します。</p></article><article class="wb-card"><h3>カード3</h3><p>内容を入力します。</p></article></div></section>',css:'.wb-section{padding:clamp(2rem,6vw,5rem)}.wb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:var(--wb-space)}.wb-card{padding:1.4rem;border:1px solid #e5e7eb;border-radius:var(--wb-radius);box-shadow:var(--wb-shadow);background:#fff}'},
{id:"faq",category:"業務",title:"FAQ",icon:"?",html:'<section class="wb-section"><h2>よくある質問</h2><details><summary>質問を入力してください</summary><p>回答を入力してください。</p></details><details><summary>質問を入力してください</summary><p>回答を入力してください。</p></details></section>',css:'details{padding:1rem 0;border-bottom:1px solid #e5e7eb}summary{cursor:pointer;font-weight:700}'},
{id:"pricing",category:"業務",title:"料金表",icon:"¥",html:'<section class="wb-section"><div class="wb-grid"><article class="wb-card"><h3>Basic</h3><strong>¥0</strong><p>基本プラン</p></article><article class="wb-card"><h3>Pro</h3><strong>¥9,800</strong><p>おすすめプラン</p></article></div></section>'},
{id:"contact",category:"業務",title:"問い合わせ",icon:"✉",html:'<section class="wb-section"><h2>お問い合わせ</h2><form class="wb-form"><label>お名前<input name="name" required></label><label>メール<input type="email" name="email" required></label><label>内容<textarea name="message" rows="5"></textarea></label><button class="wb-button" type="submit">送信</button></form></section>',css:'.wb-form{display:grid;gap:1rem;max-width:640px}.wb-form label{display:grid;gap:.35rem}.wb-form input,.wb-form textarea{padding:.8rem;border:1px solid #cfd5df;border-radius:calc(var(--wb-radius)*.7)}'},
{id:"footer",category:"セクション",title:"フッター",icon:"▔",html:'<footer class="wb-footer"><strong>Site Name</strong><small>© 2026 All rights reserved.</small></footer>',css:'.wb-footer{display:flex;justify-content:space-between;gap:1rem;padding:2rem;background:#111827;color:#fff}'},
{id:"divider",category:"基本",title:"区切り",icon:"—",html:'<hr class="wb-divider">',css:'.wb-divider{margin:2rem 0;border:0;border-top:1px solid #e5e7eb}'},
{id:"image",category:"メディア",title:"画像",icon:"▧",html:'<figure class="wb-image"><img src="https://placehold.co/1200x700" alt="画像の説明"><figcaption>画像キャプション</figcaption></figure>',css:'.wb-image img{display:block;width:100%;height:auto;border-radius:var(--wb-radius)}.wb-image figcaption{margin-top:.5rem;color:var(--wb-secondary);font-size:.9rem}'}
];
